spring.application.name=alerta-nacional

# Facebook Graph API Configuration
facebook.page.id=1013585111843916
facebook.page.access-token=EAA4JLgXW0bIBRXeU2w9FbPmPdBy4vZCOX9JxZAct4p8KIDWL6cRTaYyIoGEW5JfMc8ZCLDWavrbLQoDc7MZBI3hIWo0yaiZCGo6a7yT1299zNJZA8SSe2GhBMrl8wpmXN7UNZAsZAnI9nvc8dauAJ8Un9Go6pCfjX8FhZBYqzTDeMDWoJf20CZBAly7afB8S8TpUMhZBysMZCwZDZD
# Configuración de tamaño de archivo (Aumentar a 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

