spring.application.name=alerta-nacional

# Facebook Graph API Configuration
facebook.page.id=1013585111843916
facebook.page.access-token=EAA4JLgXW0bIBR4ZABWNAPpvLhVLxnDCrzMcDWAPeK5MHsFO2A4mvTUb8eD2zXhN2qFrKe24ZA916aZC8SDJdcKSJaz18c34vqzSUnbtuk8GTS3ZC2ly5ZB8ltCmxV5M3LVMnemynelJ8IW3TkxlxYfdIh0mLoQ4ZAfpWo6stl1ijFARTYJI0yZB96UCakkCZCYVY1kCXFgZDZD

# Configuración de tamaño de archivo (Aumentar a 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
