spring.application.name=alerta-nacional

# Facebook Graph API Configuration
facebook.page.id=1013585111843916
facebook.page.access-token=EAA4JLgXW0bIBRCqxV0PK1E9xPdwGPmETXhsqt175yytbjl2aAa4WUcXulZAsQsoSVGIEXHMWbQwqjFVdaZAAq00j3URGMZAVCyxv7FoYUZCZBs0pIQY3Qohg2UHvSNWwNW1rORttHloTlZAYfdRo0hiTYiRWwqBC6dtuYz3VhG63NwgrRdoMV5o0AfLAZATlsMqhPqncAZDZD
# Configuración de tamaño de archivo (Aumentar a 50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
